### PR TITLE
bower.json: Package this lesson for Bower

### PR DESCRIPTION
**Pull request by wking**
Docs for bower.json are [here](http://bower.io/docs/creating-packages/#bowerjson) and [here](https://github.com/bower/bower.json-spec).  Once this gets
merged, you'll want to tag a 0.1.0 release:

```
$ git tag -s -m 'version 0.1.0' v0.1.0
$ git push --tags
```

You can tweak the tag options as you see fit, but that's how I like to
sign my tags.  Then [register](http://bower.io/docs/creating-packages/#register) the package with:

```
$ bower register awk-lesson git://github.com/BillMills/awk-lesson.git
```

I'm starting with version 0.1.0 as [recommended for semantic
versioning](http://semver.org/).

Let me know if you think the content needs any tweaks.  Personally, I
think ‘lesson.md’ should be moved to ‘README.md’, which would require
a matching update to the ‘main’ entry.

### CODE REVIEW

**Comment by katieannemills** [comment]
Thanks for all the detail, that's super useful as I've never made a bower package before. I'm not familiar with 'signing tags' - can I just make a tag on GitHub without installing any more deps?

**Comment by wking** [comment]
On Tue, Mar 24, 2015 at 09:36:10PM -0700, Bill Mills wrote:

> I'm not familiar with 'signing tags'…

It's just using your GPG key to sign the tag so folks pulling from
your repository can verify that the tagged content has not been
tampered with (baring SHA-1 collisions, which are hard to do if you're
limited to textual content).  Docs in [1,2,3].

> … can I just make a tag on GitHub without installing any more deps?

Sure.  It gives a wider window for malicious parties to inject their
own content, but for an awk lesson that probably doesn't matter.  It's
more problematic if you're tagging a release in the Linux kernel or
something else that's going to get compiled and installed without a
careful read through (I certainly don't read the whole source before
building a kernel ;).

You can also make a lightweight (no metadata), unsigned tag from the
command line with:

  $ git tag v0.1.0

Or you can make an annotated (metadata and tag message), unsigned tag
with:

  $ git tag -m 'Some message' v0.1.0

See ‘-a’ and ‘-F’ for other ways to fill in the tag message.  Then
push just like you'd push a signed tag:

  $ git push --tags origin

**Comment by katieannemills** [comment]
Cool:

```
bower install study-group-awk-lesson
```

seems to work - thanks again for walking me through this! 

So, I think this workflow is really good for anything that has dependencies - getting them all with a `bower install` would be really convenient (it does handle deps, right? I'm assuming it works the same as an `npm install`). But for the awk lesson, I'm not sure it's much better than a `git clone` (if we break the lessons out into their own repos exactly as you suggested).

But on the other hand, it does teach about the culture of using packages and package managers, which is a really really good example to set.

Thanks for this - this is a serious contender for how we distribute lesson material, and enlightening for me personally :)

**Comment by wking** [comment]
Grr, it looks like Bower doesn't actually _use_ the keyword entries
yet (see bower/registry#44 and [1](https://github.com/bower/bower/issues/17#issuecomment-8548167)).  It looks like fixing that is
reasonably major work (but probably doable).  Until then, we'll have
to stuff keywords into the project name [2](http://bower.io/search/?q=awk-lesson).

It looks like work on the new registry is still in progress [3](https://github.com/bower/search-server/tree/cffc660f7ff22f09b5fbca1e46b14dbdc4f84e82#bower-search-server), and
they're using a backing database now [4](https://github.com/bower/registry/tree/7f2abeb52fcb1eab1b13950a64cb91df52241926#installation), so keyword-based searches
shouldn't be hard to put in once they deploy bower/registry.

**Comment by wking** [comment]
On Thu, Mar 26, 2015 at 01:21:16PM -0700, Bill Mills wrote:

> So, I think this workflow is really good for anything that has
> dependencies - getting them all with a `bower install` would be
> really convenient (it does handle deps, right? I'm assuming it works
> the same as an `npm install`).

Not quite.  npm is designed for server-side code, so installing
something will recursively pull all dependencies into a tree.  That
allows you to install multiple versions of the same library if one of
your deps needs <2.0 and another needs >2.0.  Bower, on the other
hand, is designed for client-side libraries, so it installs all
dependencies in a single, flat space (you don't want clients running
two versions of jQuery simultaneously).  Bower will warn you if
there's an incompatible dependency though, which is more than you'll
get out of pip (pypa/pip#988 ;).

> But for the awk lesson, I'm not sure it's much better than a `git
> clone` (if we break the lessons out into their own repos exactly as
> you suggested).

In terms of delivering the content to your local box, it's probably
worse (since we have better penetration with the ‘git’ binary).  I was
suggesting it as a way to offload discoverability:

  $ bower search awk-lesson
  Search results:

```
  study-group-awk-lesson git://github.com/BillMills/awk-lesson.git
```

  $ git search awk-lesson
  git: 'search' is not a git command. See 'git --help'.

;).  The keyword issue is unfortunate, but hopefully a temporary
 problem.

**Pull request merged**
